[package]
name = "vbcut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = { version = "0.6.6", features = ["v4_10"] }
hound = "3.5.0"
spectrum-analyzer = "1.4.0"
